linters:
  enable-all: true
  disable:
    - copyloopvar  # project is lower than Go 1.22
    - depguard  # not currently used
    - execinquery  # archived by the owner
    - gomnd  # replaced by 'mnd'
    - intrange  # project is lower than Go 1.22
    - paralleltest  # no need to enforce parallel testing

linters-settings:
  misspell:
    locale: US
