linters:
  enable-all: true
  disable:
    - copyloopvar  # project is lower than Go 1.22
    - deadcode  # replaced by 'unused'
    - depguard  # not currently used
    - execinquery  # archived by the owner
    - exhaustivestruct  # replaced by 'exhaustruct'
    - golint  # replaced by 'revive'
    - gomnd  # replaced by 'mnd'
    - ifshort  # deprecated by the owner
    - interfacer  # archived by the owner
    - intrange  # project is lower than Go 1.22
    - maligned  # replaced by 'govet'
    - nosnakecase  # replaced by 'revive'
    - paralleltest  # no need to enforce parallel testing
    - scopelint  # replaced by 'exportloopref'
    - structcheck  # replaced by 'unused'
    - varcheck  # replaced by 'unused'

linters-settings:
  misspell:
    locale: US
