version: '2'

linters:
  default: all
  disable:
    - depguard  # not currently used
    - gomodguard  # replaced by 'gomodguard_v2'
    - paralleltest  # no need to enforce parallel testing
    - testableexamples  # no need to enforce testable examples
    - wsl  # replaced by 'wsl_v5'
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - exhaustruct
          - funlen
          - goconst
          - lll
  settings:
    misspell:
      locale: US
    recvcheck:
      exclusions:
        - '*.UnmarshalText'

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      reformat-tags: false
